### ISSUE TITLE
Search by postcode / other geo

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/warm-spaces#2]

**Comment by slowe** [comment]
@gilesdring Good idea. We can do something similar to the postcode search for the DFES visualisations.

**Comment by slowe** [comment]
@gilesdring Another, less disclosive, option would be a simple place search.

**Comment by slowe** [comment]
I've added a place search as part of https://github.com/open-innovations/warm-spaces/commit/aa727b97808a3f4d92c93a75395b5a9be802cea0 This uses data I've derived from OS Open Names and should avoid requiring identifying postcode lookups.
