### ISSUE TITLE
Highlight nearest open venue

### ISSUE THREAD

**Issue by robertbrook** [open-innovations/warm-spaces#4]
When filtering the venue list by 'open', multiple results are often shown. 

It may be useful to simply highlight the first nearest venue, perhaps with a border or just text reading "This is your nearest open venue" within the venue display card. 

This would help particularly when scrolling through results, or when a user want to know only that information.

**Comment by slowe** [comment]
@robertbrook The list is ordered by distance with the closest first. Does it need separate highlighting of the first result?

**Comment by robertbrook** [comment]
It doesn't need it, but I think it would be useful, even if just a basic black border. 

For example: the nearest venue appearing on the left of three in the desktop display -

![Image 07-12-2022 at 14 21](https://user-images.githubusercontent.com/3244/206203828-5f5eae00-817b-497d-8871-dc5d9e653bcb.jpeg)

... and would still differentiate the first in the list in the smaller screen display -

![Image 07-12-2022 at 14 21](https://user-images.githubusercontent.com/3244/206203843-64c159b8-122b-4cff-914c-57e86866d4ce.jpeg)

**Comment by slowe** [comment]
I implemented a simple black border as asked.

**Comment by slowe** [comment]
I've implemented a header that says "This is your nearest open venue".
