### ISSUE TITLE
Suggested revision of venue card

### ISSUE THREAD

**Issue by robertbrook** [open-innovations/warm-spaces#6]
Deployed presentation:

![Image 07-12-2022 at 14 37](https://user-images.githubusercontent.com/3244/206220646-57cc199e-b499-4921-a724-09a7dafbc8a0.jpeg)

Suggested presentation:

![Image 07-12-2022 at 15 27](https://user-images.githubusercontent.com/3244/206220667-21e7fc07-f421-4cce-843f-8350a56d685f.jpeg)

**Comment by slowe** [comment]
@robertbrook Sorry. Only just happened to spot this. I'm slightly reluctant to hide the original opening hours because Leeds City Council only "allowed" me to start using their data again if I showed the original text because of 4 errors due to strange formatting at their end.
